#spring.datasource:
#    url: jdbc:mysql://aws-project.c0zvax1hi9xf.us-east-2.rds.amazonaws.com:3306/Project3?user=admin
#    driver: com.mysql.cj.jdbc.Driver
#    username: admin
#    password: 033747sabella
#    dialect: org.hibernate.dialect.MySQLDialect

spring:
  datasource:
  application:
    name: composite-service
  mvc:
    servlet:
      path: /composite-service
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8083


eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      key: JavaTraining