spring.datasource:
  url: jdbc:mysql://aws-project.c0zvax1hi9xf.us-east-2.rds.amazonaws.com:3306/Project3?user=admin
  driver: com.mysql.cj.jdbc.Driver
  username: admin
  password: 033747sabella
  dialect: org.hibernate.dialect.MySQLDialect

spring.data.mongodb:
  uri: mongodb+srv://root:lYY9jCphHcFHOKfV@cluster0.jb14z3u.mongodb.net/?retryWrites=true&w=majority
  database: team_project

cloud:
  aws:
    credentials:
      access-key: AKIA5TMU2UTS6443EES7
      secret-key: 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
    region:
      static: us-west-2
    stack:
      auto: false

application:
  bucket:
    name: group5-project-documents

spring:
  application:
    name: employee-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    servlet:
      path: /employee-service

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      key: JavaTraining