spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service # service name
          predicates:
            - Path=/employee-service/** # url pattern
        - id: housing-service
          uri: lb://housing-service
          predicates:
            - Path=/housing-service/**
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/application-service/**
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/email-service/**
        - id: composite-service
          uri: lb://composite-service
          predicates:
            - Path=/composite-service/**

server:
  port: 9000

#The Gateway will also be registered at the Eureka server
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
